Repository RePro3D-Praxisproject/repro3d-backend, pull requests merged in 2024-05, with the labels that each got.

#24 refactor: Configure infrastructure RP-131
  AuthService/src/main/resources/application.properties
  BillingService/src/main/resources/application.properties
  OrderService/src/main/resources/application.properties
  PrinterService/src/main/resources/application.properties
Labels: refactor

#26 docs: add openApi specification to Authentication service RP-139
  AuthService/openApi/OpenApi.yml
  BillingService/openApi/OpenApi.yml
  OrderService/openApi/OpenApi.yml
  PrinterService/openApi/OpenApi.yml
Labels: documentation, enhancement

#27 feat: add backend side password hashing and rolesetting when registering RP-22
  AuthService/src/main/java/org/repro3d/service/UserService.java
Labels: enhancement

#33 feat: Add "nulling" of rc_id in Orders when the RC gets deleted
  BillingService/src/main/java/org/repro3d/repository/OrderRepository.java
  BillingService/src/main/java/org/repro3d/service/RedeemCodeService.java
Labels: enhancement

#35 feat: Add retrieving of all `OrderItems` by `orderId`
  API-Gateway/src/main/java/org/repro3d/apigateway/EntryPointApiGateway.java
  BillingService/src/main/java/org/repro3d/model/Order.java
  BillingService/src/main/java/org/repro3d/service/ReceiptService.java
  OrderService/src/main/java/org/repro3d/controller/OrderItemsController.java
  OrderService/src/main/java/org/repro3d/model/Job.java
  OrderService/src/main/java/org/repro3d/model/Order.java
  OrderService/src/main/java/org/repro3d/model/OrderItems.java
  OrderService/src/main/java/org/repro3d/repository/OrderItemsRepository.java
  OrderService/src/main/java/org/repro3d/service/OrderItemsService.java
  OrderService/src/test/java/org/repro3d/service/OrderItemsServiceTest.java
  OrderService/src/test/java/org/repro3d/service/OrderServiceTest.java
Labels: enhancement

#37 docs: add javadoc to api gateway module RP-173
  API-Gateway/src/main/java/org/repro3d/apigateway/AuthorizationHeaderFilter.java
  API-Gateway/src/main/java/org/repro3d/apigateway/EntryPointApiGateway.java
  AuthService/src/main/java/org/repro3d/SecurityConfig.java
  AuthService/src/main/java/org/repro3d/controller/AuditLogController.java
  AuthService/src/main/java/org/repro3d/controller/FrontConfigController.java
  AuthService/src/main/java/org/repro3d/controller/LogActionController.java
  AuthService/src/main/java/org/repro3d/controller/RoleController.java
  AuthService/src/main/java/org/repro3d/controller/UserController.java
  AuthService/src/main/java/org/repro3d/model/AuditLog.java
  AuthService/src/main/java/org/repro3d/model/FrontConfig.java
  AuthService/src/main/java/org/repro3d/model/LogAction.java
  AuthService/src/main/java/org/repro3d/model/User.java
  AuthService/src/main/java/org/repro3d/repository/AuditLogRepository.java
  AuthService/src/main/java/org/repro3d/repository/FrontConfigRepository.java
  AuthService/src/main/java/org/repro3d/repository/LogActionRepository.java
  AuthService/src/main/java/org/repro3d/repository/RoleRepository.java
  AuthService/src/main/java/org/repro3d/repository/UserRepository.java
  AuthService/src/main/java/org/repro3d/service/FrontConfigService.java
  AuthService/src/main/java/org/repro3d/service/UserDetailsServiceImpl.java
  BillingService/src/main/java/org/repro3d/controller/ReceiptController.java
  BillingService/src/main/java/org/repro3d/controller/RedeemCodeController.java
  BillingService/src/main/java/org/repro3d/model/Order.java
  BillingService/src/main/java/org/repro3d/model/Receipt.java
  BillingService/src/main/java/org/repro3d/model/RedeemCode.java
  BillingService/src/main/java/org/repro3d/model/Role.java
  BillingService/src/main/java/org/repro3d/model/User.java
  OrderService/src/main/java/org/repro3d/model/User.java
  OrderService/src/main/java/org/repro3d/repository/UserRepository.java
  README.md
Labels: documentation
