Repository RePro3D-Praxisproject/repro3d-backend, pull requests merged in 2024-04, with the labels that each got.

#7 feat: Add CRUD for OrderService module RP-60
  OrderService/pom.xml
  OrderService/src/main/java/repro3d/EntryPointOrderService.java
  OrderService/src/main/java/repro3d/controller/ItemController.java
  OrderService/src/main/java/repro3d/controller/OrderController.java
  OrderService/src/main/java/repro3d/controller/OrderItemsController.java
  OrderService/src/main/java/repro3d/model/Item.java
  OrderService/src/main/java/repro3d/model/Order.java
  OrderService/src/main/java/repro3d/model/OrderItems.java
  OrderService/src/main/java/repro3d/repository/ItemRepository.java
  OrderService/src/main/java/repro3d/repository/OrderItemsRepository.java
  OrderService/src/main/java/repro3d/repository/OrderRepository.java
  OrderService/src/main/java/repro3d/service/ItemService.java
  OrderService/src/main/java/repro3d/service/OrderItemsService.java
  OrderService/src/main/java/repro3d/service/OrderService.java
  OrderService/src/main/java/repro3d/utils/ApiResponse.java
  OrderService/src/test/java/org/repro3d/service/OrderItemsServiceTest.java
  OrderService/src/test/java/org/repro3d/service/OrderServiceTest.java
  PrinterService/src/main/java/org/repro3d/EntryPointServices.java
  PrinterService/src/main/java/org/repro3d/controller/ItemController.java
  PrinterService/src/main/java/org/repro3d/model/Item.java
  PrinterService/src/test/java/org/repro3d/service/ItemServiceTest.java
  pom.xml
Labels: enhancement

#9 feat: Add proper foreign key connection for OrderService module RP-60
  OrderService/pom.xml
  OrderService/src/main/java/repro3d/controller/ItemController.java
  OrderService/src/main/java/repro3d/controller/OrderController.java
  OrderService/src/main/java/repro3d/controller/OrderItemsController.java
  OrderService/src/main/java/repro3d/model/Item.java
  OrderService/src/main/java/repro3d/model/Job.java
  OrderService/src/main/java/repro3d/model/Order.java
  OrderService/src/main/java/repro3d/model/OrderItems.java
  OrderService/src/main/java/repro3d/model/Printer.java
  OrderService/src/main/java/repro3d/model/Role.java
  OrderService/src/main/java/repro3d/model/Status.java
  OrderService/src/main/java/repro3d/model/User.java
  OrderService/src/main/java/repro3d/repository/JobRepository.java
  OrderService/src/main/java/repro3d/repository/UserRepository.java
  OrderService/src/main/java/repro3d/service/OrderItemsService.java
  OrderService/src/main/java/repro3d/service/OrderService.java
  OrderService/src/main/resources/application.properties
  OrderService/src/test/java/org/repro3d/service/OrderItemsServiceTest.java
  OrderService/src/test/java/org/repro3d/service/OrderServiceTest.java
Labels: enhancement

#13 feat: Add AuthService BasicAuth and Gateway API with transparent header forwarding RP-22
  API-Gateway/pom.xml
  API-Gateway/src/main/java/repro3d/apigateway/AuthorizationHeaderFilter.java
  API-Gateway/src/main/java/repro3d/apigateway/EntryPointApiGateway.java
  API-Gateway/src/main/resources/application.properties
  AuthService/pom.xml
  AuthService/src/main/java/repro3d/SecurityConfig.java
  AuthService/src/main/java/repro3d/service/UserDetailsServiceImpl.java
  AuthService/src/main/resources/application.properties
  DiscoveryServer/pom.xml
  DiscoveryServer/src/main/java/org/repro3d/discoveryserver/EntryPointDiscoveryServer.java
  DiscoveryServer/src/main/resources/application.properties
  OrderService/src/main/resources/application.properties
Labels: enhancement

#14 feat: Add customer registration and login RP-22
  API-Gateway/src/main/java/repro3d/apigateway/EntryPointApiGateway.java
  AuthService/src/main/java/repro3d/SecurityConfig.java
  AuthService/src/main/java/repro3d/model/User.java
Labels: enhancement

#15 feat: add getApikeyById to service and controller for printer RP-63
  PrinterService/pom.xml
  PrinterService/src/main/java/repro3d/EntryPointPrinterService.java
  PrinterService/src/main/java/repro3d/controller/PrinterController.java
  PrinterService/src/main/java/repro3d/service/PrinterService.java
  PrinterService/src/main/resources/application.properties
Labels: enhancement

#19 feat: add /api to controller request paths RP-53
  API-Gateway/src/main/java/repro3d/apigateway/EntryPointApiGateway.java
  API-Gateway/src/main/resources/application.properties
  AuthService/src/main/java/repro3d/SecurityConfig.java
  AuthService/src/main/java/repro3d/controller/AuditLogController.java
  AuthService/src/main/java/repro3d/controller/LogActionController.java
  AuthService/src/main/java/repro3d/controller/RoleController.java
  AuthService/src/main/java/repro3d/controller/UserController.java
  OrderService/src/main/java/repro3d/controller/ItemController.java
  OrderService/src/main/java/repro3d/controller/OrderController.java
  OrderService/src/main/java/repro3d/controller/OrderItemsController.java
  OrderService/src/main/java/repro3d/model/Item.java
  PrinterService/src/main/java/repro3d/controller/JobController.java
  PrinterService/src/main/java/repro3d/controller/PrinterController.java
  PrinterService/src/main/java/repro3d/controller/StatusController.java
Labels: bug

#17 feat: Add BillingService module RP-76
  BillingService/pom.xml
  BillingService/src/main/java/org/repro3d/EntryPointBillingService.java
  BillingService/src/main/java/org/repro3d/controller/ReceiptController.java
  BillingService/src/main/java/org/repro3d/controller/RedeemCodeController.java
  BillingService/src/main/java/org/repro3d/model/Order.java
  BillingService/src/main/java/org/repro3d/model/Receipt.java
  BillingService/src/main/java/org/repro3d/model/RedeemCode.java
  BillingService/src/main/java/org/repro3d/model/Role.java
  BillingService/src/main/java/org/repro3d/model/User.java
  BillingService/src/main/java/org/repro3d/repository/OrderRepository.java
  BillingService/src/main/java/org/repro3d/repository/ReceiptRepository.java
  BillingService/src/main/java/org/repro3d/repository/RedeemCodeRepository.java
  BillingService/src/main/java/org/repro3d/service/ReceiptService.java
  BillingService/src/main/java/org/repro3d/service/RedeemCodeService.java
  BillingService/src/main/java/org/repro3d/utils/ApiResponse.java
  BillingService/src/main/resources/application.properties
  BillingService/src/test/java/org/repro3d/service/ReceiptServiceTest.java
  BillingService/src/test/java/org/repro3d/service/RedeemCodeServiceTest.java
  BillingService/src/test/resources/application-test.properties
  OrderService/src/main/java/org/repro3d/model/Order.java
  OrderService/src/main/java/org/repro3d/model/RedeemCode.java
  OrderService/src/main/java/org/repro3d/repository/RedeemCodeRepository.java
  OrderService/src/main/java/org/repro3d/service/OrderService.java
  OrderService/src/test/java/org/repro3d/service/OrderServiceTest.java
Labels: enhancement

#16 refactor: Change the PR template RP-47
  .github/pull_request_template.md
Labels: bug, enhancement
